version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip install -r requirements.txt -r requirements-dev.txt
      - run:
          name: Flake8
          command: flake8 .
      - run:
          name: PyTests
          command: py.test tests
